// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhygbhglrfmurnbeguay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoeWdiaGdscmZtdXJuYmVndWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTM1MDAsImV4cCI6MjA2MDkyOTUwMH0.UN6xct3LCKGXcgnnXe3ZczdwwCnvBDkUdoY9mHtbVaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);